version: "3"

services:
  ms1:
    build: user/target/docker
    ports:
    - "8001:8001"
    depends_on:
    - db

  ms2:
    build: team/target/docker
    ports:
    - "8002:8002"
    depends_on:
    - db

  db:
    image: mysql:5.7.17
    ports:
    - "3306:3306"
    volumes:
    - mysql-data:/var/lib/mysql
    environment:
    - MYSQL_USER=root
    - MYSQL_PASSWORD=11042.
    - MYSQL_ROOT_PASSWORD=11042.

volumes:
  mysql-data:
    external: false

